# Generated by Django 4.1.5 on 2023-04-06 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_on',
            field=models.DateField(verbose_name=datetime.datetime(2023, 4, 6, 19, 52, 18, 910555)),
        ),
    ]
