# Generated by Django 4.2.1 on 2023-05-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_app', '0003_alter_tasks_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={},
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='iscomplete',
        ),
        migrations.AddField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('WORKING', 'Working'), ('DONE', 'Done'), ('OVERDUE', 'Overdue')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='tasks',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(default='COMPLETE TASKS'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
